language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-29.0.3
    - android-29

before_install:
  - yes | sdkmanager "platforms;android-29"

script: "./gradlew build --stacktrace"
